#!/software/R-4.1.0/bin/Rscript 
#################################################################
# PDX_bwa_mem_mapping_jobs_from_master_manif.R
# This script takes an MAster manifest generated from 6591_master_manifest_creation_RNAseq.R to create series of files with a series of command job submission to import, sort, transform to fastq, map with STAR
# and generate counts with htseqcount plus some quality controls for the read nucleotide composition and TIN (currently not working)
# All of this with the Rat genome assembly (Rnor6.0 plus 92 ERCC spike ins) 
#
#  The Project folder should have the following  structure before running this program:
#  /My_project_folder/
#   ├── manifests/My_cram_manifest_INFO_from_iRODS.txt
#   ├── BAMS
#   │   └── WES_UNFILT
#   ├── fastqs
# The program will create the  following directories:
# /My_project_folder/
#     /fastqs
#       /PDID
#     /logs
#       /cramtofastqs
#       /STAR_logs
#       /htseq_logs
#       /RSeQC_logs
#     /qc_plots/
#       /nucleaotid_comp_bias
#       /read_quality
#     /STAR2_7_9a_bams
#     /htseq_counts/
# 
# 
# 
#Created: 25/08/2021
#Updated: 20/07/2022 - Commenting unused code and additions of per sample folders under the BAM output structure
#Author: Martin Del Castillo Velasco-Herrera - mdc1@sanger.ac.uk
###################################################################
progname<-"PDX_bwa_mem_mapping_jobs_from_master_manif.R"

#Loading Libraries
suppressMessages(library(optparse))

#Get the options for tthe script
####### Set the options list of the program
option_list<- list(
  make_option(c("--manifest"), action="store_true", default=NA, type="character", help="This is the project iRODs manifest file name generated by sequencescape project ID number using Build_manifest_from_irods_cram_information.R
                IT should be locatet in the folder /projectdir/manifests/ for this command to work"), 
  make_option(c("--projectdir" ), action="store_true",type="character", default=NA, help="This is the location where the main project folder is (if provided, else it will assume the current directory)")
)
#### Indicate that the file follows to the options used
parser<- OptionParser(usage = paste(progname, " [options] --manifest SeqscapeID_canappsID_master_manifest_wmetadata_for_proj.txt --projectdir  /My_project_folder/ ",sep=""), option_list=option_list)
arguments<- parse_args(parser, positional_arguments = 0) # no files after the options shoudl be provided

# get command line options, if help option encountered print help and exit,
# otherwise if options not found on command line then set defaults,
opt<-arguments$options


#Verify that the outidr was set
if(is.na(opt$projectdir)){
  projectdir<-paste(getwd(),"/",sep="")
} else {
  projectdir<-opt$projectdir
}
#Verify that the input manifest exitst was set 
manif_name<-file.path(projectdir,"manifests",opt$manifest)
if(!file.exists(manif_name)){
  stop(paste("The manifest file:", manif_name, "doesn't exits. Check file or see the help for requirements", sep=""))
}
#Getting the study id
studyid<-unlist(strsplit(opt$manifest, split = "_",fixed = T) )[1]

#Write some output starting message
write(paste("#########################################\n", progname, date(),"The study ID found from manifest name is: ",studyid, "\nThe Manifest provided:", opt$manifest,"\n",
            "The projectdir provided is:", projectdir, "\n", "The project manifest found is: ",manif_name, "\n",sep=" "), stdout())

#######################################################################
#Defining the directories for the analyses and GENERAL VARIABLES

#Set of folders for the outputs
fqfolder<-file.path(projectdir, "fastqs")
logfolder<-paste(projectdir, "/logs", sep="")
manifdir<-file.path(projectdir, "manifests")
#create the folder for the mapping results 
bamdir<-file.path(projectdir,"BAMS", "WES_UNFILT")
bwamem_maplogdir<-file.path(logfolder, "bwamem_logs")
persampl_mergelogdir<-file.path(logfolder, "persamp_merge_logs")


#Make the folders
dir.create(fqlogfolder, recursive = TRUE)
dir.create(bamdir, recursive = TRUE)
dir.create(bwamem_maplogdir, recursive = TRUE)
dir.create(persampl_mergelogdir, recursive = TRUE)

#PAHTS to the programs required
samtools<-"/software/CASM/modules/installs/samtools/samtools-1.13/bin/samtools"
#bwa mem module for the latest version of bwa mem module 
bwamem<-"module load bwa/0.7.17 ; bwa mem"
# BWA MEM reference index directory and GTF for -NOD/ShiLtJ_V1 reference for PDX filtering 
bwamem_nodv1_ref_fasta<-"/lustre/scratch124/casm/team113/ref/NOD_ShiLtJ_V1_PDX_ref/genome.fa"
# BWA MEM reference index directory and GTF for -NOD/ShiLtJ_V3 reference for PDX filtering 
bwamem_nodv3_ref_fasta<-"/lustre/scratch124/casm/team113/ref/NOD_ShiLtJ_V3/NOD_ShiLtJ_V3_PDX_ref/genome.fa"


######################
#EXMAPLEs of job to transform cram from iRODs to fastq
# bsub -q normal -M 8000 -R'select[mem>8000] rusage[mem=8000] span[hosts=1]' -n 4 -o /lustre/scratch119/casm/team113da/users/mdc1/6352_project_tests/logs/cramtofastqs/cramtofq_21.o -e /lustre/scratch119/casm/team113da/users/mdc1/6352_project_tests/logs/cramtofastqs/cramtofq_21.e 'iget /seq/illumina/runs/38/38900/lane1/plex21/38900_1#21.cram - | /software/CASM/modules/installs/samtools/samtools-1.13/bin/samtools collate -u --threads 4 -O - |/software/CASM/modules/installs/samtools/samtools-1.13/bin/samtools fastq --threads 4 -1 /lustre/scratch119/casm/team113da/users/mdc1/6352_project_tests/fastqs/6352STDY10233950_R1.fastq.gz -2 /lustre/scratch119/casm/team113da/users/mdc1/6352_project_tests/fastqs/6352STDY10233950_R2.fastq.gz -n '

#############################################################################################
# 1. Read the file  manifest file  ------------------
manif<-read.csv(manif_name, header=TRUE, stringsAsFactors=FALSE, sep="\t")
manif$sample <- manif$sample_supplier_name
#Add the fastq names
manif$fastq1 <- file.path(fqfolder, manif$sample, paste(manif$sample, gsub(".cram","", manif$cram, fixed = T), "R1.fastq.gz", sep="_")) 
manif$fastq2 <- file.path(fqfolder, manif$sample, paste(manif$sample, gsub(".cram","", manif$cram, fixed = T), "R2.fastq.gz", sep="_")) 


#To take as a test I will generate things first for the biggest sample
#test_sampl<-manif[manif$total_reads==228701454,]

#############################################################################################
# 2. Create the sh file that will submit  the jobs for mouse mapping from FASTA transformation  ------------------

#############################################################################################
# 3. Create the per sample manifest   ------------------
#In this case since the samples were sequenced into a single lane  there is no need get a manifest with all the information per unique sample

#############################################################################################
# 4. Create the sh file that will submit the mapping with STAR agains NOD/ShiLtJ_V1 for Tumours only------------------
#bsub -q long -J "PD53330a" -M 16000 -R"select[mem>16000] rusage[mem=16000] span[ptile=12]" -n 12  
#-o /lustre/scratch116/casm/team113/projects/4624_TSG_knockout_in_hiPSCs_Jyoti_Clara/STAR2_5_bams/logs/4624STDY6739364STAR_run.o 
#-e /lustre/scratch116/casm/team113/projects/4624_TSG_knockout_in_hiPSCs_Jyoti_Clara/STAR2_5_bams/logs/4624STDY6739364STAR_run.e 
#'/software/pkgg/bwa/0.7.17/bin/bwa mem 
#-t 12 
# -Y 
# -K 100000000
# -R "@RG\tID:COL_${INDEX}\tSM:COL_${INDEX}"
# "ID:\tLB:6735728\tSM:PD5330a\tPL:ILLUMINA"

#/lustre/scratch124/casm/team113/ref/NOD_ShiLtJ_V1_PDX_ref/genome.fa 
# PD53330a_R1.fastq.gz
# PD53330a_R2.fastq.gz
# bwa mem genome.fa PD53330a_41760_1#2_R1.fastq.gz PD53330a_41760_1#2_R2.fastq.gz | samtools sort -m 1G -@ 10 -o PD53330a_NOD_PDXV1.aln.sort.out.bam - ;
# samtools index PD53330a_NOD_PDXV1.aln.sort.out.bam

#Identify the tumour samples since this will be the only ones to process for further analyses
tumour_pos<- manif$Proc.as.Tum=="Y"
tumour_sample_names<- unique(manif$sample[tumour_pos])

#Create the two directories that will be created to store the mouse mapped files. 
refnam<-"NOD_PDXV1"
nodv1_bamfile_dir<- file.path(projectdir,"BAMS", "NOD_mapping", refnam)
dir.create(nodv1_bamfile_dir, recursive = T)

#Generate the set of mapping commands - NODv1
i<-1
bamfile<-NULL
cmds<-NULL
bam_path<-NULL
mergedbam_path<-NULL
tmanif<-manif
for (i in 1:dim(tmanif)[1]){
  sdoutf<-NULL
  serrf<-NULL
  temp<-tmanif[i,]
  cmd<-NULL
  bam_prefix<-NULL
  bam_sampdir<-NULL
  tbamp<-NULL
  tmerbamp<-NULL
  # give name to errorfiles
  sdoutf<-file.path(bwamem_maplogdir, paste("bwamem_mapping_log_",refnam,"_", i,".o", sep = ""))
  serrf<-file.path(bwamem_maplogdir, paste("bwamem_mapping_log_",refnam,"_", i,".e", sep = ""))
  bam_sampdir<-file.path(nodv1_bamfile_dir, temp$sample)
  print(paste("Creating the output directory for mapping of sample", temp$sample))
  dir.create(bam_sampdir)
  bam_prefix<-file.path(bam_sampdir, paste(temp$sample, "_", refnam, ".", sep=""))
  tbamp<-paste(bam_prefix, paste(temp$id_run,"_",temp$lane, "#",temp$tag_index,sep=""), ".aln.sort.out.bam", sep="")
  tmerbamp<-paste(bam_prefix, ".sample.aln.sort.out.bam", sep="") # For the merged bamfile for the sample
  #Section that creates the farm command to submit the job the job submission 
  # should look like this
  #Memory
  cmd<-as.character(paste("bsub -q long -M 36000 -R",shQuote("select[mem>36000] rusage[mem=36000] span[hosts=1]") , " -n 12 -o ", sdoutf," -e ",serrf,
                          " '", bwamem, " -t 12 -Y -K 100000000 -R ",
                          #Read group 
                          "\"",  paste("@RG",paste(paste("ID:",temp$id_run,"_",temp$lane, "#",temp$tag_index,sep=""),paste("LB:",temp$library_id,sep=""), paste("SM:",temp$sample_supplier_name,sep=""), "PL:ILLUMINA", sep="\\t"), sep="\\t"), "\"",
                          #Reference genome 
                          " ", bwamem_nodv1_ref_fasta, " ",
                          temp$fastq1, " ", temp$fastq2 ,
                          " | ", samtools , " sort -m 1G -@ 10 -o ", tbamp, " - ; ",
                          samtools, " index ", tbamp,
                          " '",
                          sep=""))  
  #ADD the jobs
  cmds<-c(cmds,cmd)
  #add to the list of bampaths for bams per RUN_Lane#TagID
  bam_path<-c(bam_path, tbamp)
  #add to the list of bampaths for bams per RUN_Lane#TagID
  mergedbam_path<- c(mergedbam_path, tmerbamp)
}

#Add the bampaths to the manifes
manif$bam_run_lane_tid_path_nodv1<-bam_path
manif$bam_psample_path_nodv1<-mergedbam_path
#Create the sh file 
# write.table(c("#!/bin/sh", cmds), file=file.path(projectdir,"scripts", paste("bwamem_mapping_perlanrun_to_",refnam, "_jobs.sh", sep="")), quote = F, col.names = F, row.names = F, sep = "\n")
write.table(c("#!/bin/sh", cmds[tumour_pos]), file=file.path(projectdir,"scripts", paste("bwamem_mapping_perlanrun_to_",refnam, "_tum_only_jobs.sh", sep="")), quote = F, col.names = F, row.names = F, sep = "\n")

#############################################################################################
# 5. Create the sh file that will submit the mapping with STAR against NOD/ShiLtJ_V3 ------------------
#Create the two directories that will be created to store the mouse mapped files. 
refnam<-"NOD_PDXV3"
nodv3_bamfile_dir<- file.path(projectdir,"BAMS", "NOD_mapping", refnam)
dir.create(nodv3_bamfile_dir, recursive = T)

#Generate the set of mapping commands - NODv1
# i<-1
bamfile<-NULL
cmds<-NULL
bam_path<-NULL
mergedbam_path<-NULL
tmanif<-manif
for (i in 1:dim(tmanif)[1]){
  sdoutf<-NULL
  serrf<-NULL
  temp<-tmanif[i,]
  cmd<-NULL
  bam_prefix<-NULL
  bam_sampdir<-NULL
  tbamp<-NULL
  tmerbamp<-NULL
  # give name to errorfiles
  sdoutf<-file.path(bwamem_maplogdir, paste("bwamem_mapping_log_",refnam,"_", i,".o", sep = ""))
  serrf<-file.path(bwamem_maplogdir, paste("bwamem_mapping_log_",refnam,"_", i,".e", sep = ""))
  bam_sampdir<-file.path(nodv3_bamfile_dir, temp$sample)
  print(paste("Creating the output directory for mapping of sample", temp$sample))
  dir.create(bam_sampdir)
  bam_prefix<-file.path(bam_sampdir, paste(temp$sample, "_", refnam, ".", sep=""))
  tbamp<-paste(bam_prefix, paste(temp$id_run,"_",temp$lane, "#",temp$tag_index,sep=""), ".aln.sort.out.bam", sep="")
  tmerbamp<-paste(bam_prefix, ".sample.aln.sort.out.bam", sep="") # For the merged bamfile for the sample
  #Section that creates the farm command to submit the job the job submission 
  # should look like this
  #Memory
  cmd<-as.character(paste("bsub -q long -M 36000 -R",shQuote("select[mem>36000] rusage[mem=36000] span[hosts=1]") , " -n 12 -o ", sdoutf," -e ",serrf,
                          " '", bwamem, " -t 12 -Y -K 100000000 -R ",
                          #Read group 
                          "\"",  paste("@RG",paste(paste("ID:",temp$id_run,"_",temp$lane, "#",temp$tag_index,sep=""),paste("LB:",temp$library_id,sep=""), paste("SM:",temp$sample_supplier_name,sep=""), "PL:ILLUMINA", sep="\\t"), sep="\\t"), "\"",
                          #Reference genome 
                          " ", bwamem_nodv3_ref_fasta, " ",
                          temp$fastq1, " ", temp$fastq2 ,
                          " | ", samtools , " sort -m 1G -@ 10 -o ", tbamp, " - ; ",
                          samtools, " index ", tbamp,
                          " '",
                          sep=""))  
  #ADD the jobs
  cmds<-c(cmds,cmd)
  #add to the list of bampaths for bams per RUN_Lane#TagID
  bam_path<-c(bam_path, tbamp)
  #add to the list of bampaths for bams per RUN_Lane#TagID
  mergedbam_path<- c(mergedbam_path, tmerbamp)
}

#Add the bampaths to the manifes
manif$bam_run_lane_tid_path_nodv3<-bam_path
manif$bam_psample_path_nodv3<-mergedbam_path
#Create the sh file 
# For all samples
# write.table(c("#!/bin/sh", cmds), file=file.path(projectdir,"scripts", paste("bwamem_mapping_perlanrun_to_",refnam, "_jobs.sh", sep="")), quote = F, col.names = F, row.names = F, sep = "\n")
write.table(c("#!/bin/sh", cmds[tumour_pos]), file=file.path(projectdir,"scripts", paste("bwamem_mapping_perlanrun_to_",refnam, "_tum_only_jobs.sh", sep="")), quote = F, col.names = F, row.names = F, sep = "\n")

#############################################################################################
# 6.Create the jobs for file merging      ------------------

# Create the two directories that will be created to store the mouse mapped files. 
cmds_nodv1<-NULL
cmds_nodv3<-NULL
for(i in 1:length(tumour_sample_names)){
  print(paste0("Processing sample ", tumour_sample_names[i], "NodV1" ))
  tempsamp<-NULL
  cmd<-NULL
  sdoutf<- NULL
  serrf<- NULL
  #Assing job output names 
  sdoutf<-file.path(persampl_mergelogdir, paste("samtools_psamp_merge_log_nodv1_", i,".o", sep = ""))
  serrf<-file.path(persampl_mergelogdir, paste("samtools_psamp_merge_log_nodv1_", i,".e", sep = ""))
  tempsamp<- tumour_sample_names[i]
  temp<-manif[ manif$sample==tempsamp,  ]
  #Command for Nodv1 per sample file and index
  cmd<-as.character(paste("bsub -q normal -M 16000 -R",shQuote("select[mem>16000] rusage[mem=16000] span[hosts=1]") , " -n 8 -o ", sdoutf," -e ",serrf,
                          " '", samtools,  " merge -@ 8 -o ", temp$bam_psample_path_nodv1[1], " ", 
                          #the names of the lane bam files NODV1
                          paste(temp$bam_run_lane_tid_path_nodv1, collapse = " "),  " ; ",
                          # index the bam file 
                          samtools, " index ", temp$bam_psample_path_nodv1[1],
                          " '",
                          sep=""))  
  #Append the command to the list of NODv1 merging
  cmds_nodv1<- c(cmds_nodv1, cmd)
  
  #Command for Nodv3 per sample file and index
  print(paste0("Processing sample ", tumour_sample_names[i], "NodV3" ))
  #Assing job output names 
  sdoutf<-file.path(persampl_mergelogdir, paste("samtools_psamp_merge_log_nodv3_", i,".o", sep = ""))
  serrf<-file.path(persampl_mergelogdir, paste("samtools_psamp_merge_log_nodv3_", i,".e", sep = ""))
  cmd<-as.character(paste("bsub -q normal -M 16000 -R",shQuote("select[mem>16000] rusage[mem=16000] span[hosts=1]") , " -n 8 -o ", sdoutf," -e ",serrf,
                          " '", samtools,  " merge -@ 8 -o ", temp$bam_psample_path_nodv3[1], " ", 
                          #the names of the lane bam files NODV3
                          paste(temp$bam_run_lane_tid_path_nodv3, collapse = " "),  " ; ",
                          # index the bam file 
                          samtools, " index ", temp$bam_psample_path_nodv3[1],
                          " '",
                          sep=""))  
  #Append the command to the list of NODv3 merging
  cmds_nodv3<- c(cmds_nodv3, cmd)
}

#Generate the .sh files with the submissions 
write.table(c("#!/bin/sh", cmds_nodv1), file=file.path(projectdir,"scripts", paste("samtools_psample_merge_nodv1_tum_only_jobs.sh", sep="")), quote = F, col.names = F, row.names = F, sep = "\n")
write.table(c("#!/bin/sh", cmds_nodv3), file=file.path(projectdir,"scripts", paste("samtools_psample_merge_nodv3_tum_only_jobs.sh", sep="")), quote = F, col.names = F, row.names = F, sep = "\n")


#############################################################################################
# 7. Write the manifest with the path files      ------------------

#Remove the per sample files for the non tumour samples 
#Add the bampaths to the manifes
manif$bam_run_lane_tid_path_nodv3[!tumour_pos]<-NA
manif$bam_psample_path_nodv3[!tumour_pos]<-NA
#Add the bampaths to the manifes
manif$bam_run_lane_tid_path_nodv1[!tumour_pos]<-NA
manif$bam_psample_path_nodv1[!tumour_pos]<-NA

#Name of the outfile manif
out_manif_name<-file.path(projectdir,"manifests",gsub(pattern = ".txt", "_psamp_mouse.txt", opt$manifest))
write.table(manif, file=out_manif_name, quote = F, col.names = T, row.names = F, sep = "\t")

